//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataformaEncontreMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESAPARECIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DESAPARECIDO()
        {
            this.LOCALIZACAO = new HashSet<LOCALIZACAO>();
        }
    
        public int COD_DESAPARECIDO { get; set; }
        public string NOME_DESAPARECIDO { get; set; }
        public string RG_DESAPARECIDO { get; set; }
        public string CPF_DESAPARECIDO { get; set; }
        public string BO_DESAPARECIDO { get; set; }
        public Nullable<System.TimeSpan> HORARIO_DESAPARECIDO { get; set; }
        public System.DateTime DATA_DESAPARECIDO { get; set; }
        public string CARACTERISTICAS_DESAPARECIDO { get; set; }
        public string FOTO_DESAPARECIDO { get; set; }
        public Nullable<int> COD_USUARIO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCALIZACAO> LOCALIZACAO { get; set; }
    }
}
