//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataformaEncontreMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCALIZACAO
    {
        public int COD_LOCALIZACAO { get; set; }
        public int COD_DESAPARECIDO { get; set; }
        public string LATITUDE_LOCALIZACAO { get; set; }
        public string LONGITUDE_LOCALIZACAO { get; set; }
    
        public virtual DESAPARECIDO DESAPARECIDO { get; set; }
    }
}
